# Generated by Django 6.1.1 on 2026-09-09 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_bio_user_department_user_target_daily_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_notification_ids', models.JSONField(blank=True, default=list)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
