# Generated by Django 6.1.1 on 2026-09-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usernotificationstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='target_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
    ]
