# Generated by Django on 2026-09-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_credits',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='total_credits',
            field=models.DecimalField(blank=True, decimal_places=1, default=140.0, max_digits=5, null=True),
        ),
    ]
