# Generated by Django 6.1.1 on 2026-09-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_completed_credits_user_current_trimester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='completed_credits',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_trimester',
            field=models.CharField(blank=True, default='1st Trimester', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_credits',
            field=models.DecimalField(decimal_places=1, default=140.0, max_digits=5),
        ),
    ]
