# Generated by Django 6.1.1 on 2026-09-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_completed_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='completed_credits',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_credits',
            field=models.DecimalField(blank=True, decimal_places=1, default=140.0, max_digits=5, null=True),
        ),
    ]
