# Generated by Django 6.1.1 on 2026-09-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_completed_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_trimester',
            field=models.CharField(blank=True, default='1st Trimester', max_length=50, null=True),
        ),
    ]
