# Generated by Django 6.1.1 on 2026-09-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_current_trimester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_onboarded',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='opt_in_leaderboard',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
