"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Environment variables
env = environ.Env()
environ.Env.read_env(BASE_DIR.parent / ".env")


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = env(
    "DJANGO_SECRET_KEY",
    default="django-insecure-jgjok3^26293l*4gus^)&eas*=7ar-djvdktlc^ge%_a=7t=w8",
)

DEBUG = env.bool("DJANGO_DEBUG", default=True)

ALLOWED_HOSTS = env.list(
    "ALLOWED_HOSTS",
    default=["*"],
)


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    # Local apps
    "accounts",
    "planner",
    "grades",
    "tracker",
    "community",
    "ai",
    "materials",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # CORS
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# CORS
# ============================================================

CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS",
    default=[
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://0.0.0.0:5173",
        "http://localhost:3000",
        "https://uiu-student-brain.onrender.com",
    ],
)
CORS_ALLOW_ALL_ORIGINS = env.bool("CORS_ALLOW_ALL_ORIGINS", default=True)
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = env.list(
    "CSRF_TRUSTED_ORIGINS",
    default=[
        "https://uiu-student-brain.onrender.com",
        "https://*.onrender.com",
        "https://*.vercel.app",
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ],
)


# ============================================================
# URL / AUTH
# ============================================================

ROOT_URLCONF = "config.urls"

AUTH_USER_MODEL = "accounts.User"


# ============================================================
# DJANGO REST FRAMEWORK
# ============================================================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "120/minute",
        "user": "1200/minute",
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

# ============================================================
# HTTP SECURITY & COOKIE PROTECTION
# ============================================================
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = "Lax"
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = "same-origin"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = "config.wsgi.application"


# ============================================================
# DATABASE
# ============================================================

import socket

# Support TiDB / MySQL connections with PyMySQL
try:
    import pymysql
    import pymysql.connections

    if not getattr(pymysql.connections.Connection, "_is_ssl_mode_patched", False):
        _orig_init = pymysql.connections.Connection.__init__

        def _patched_init(self, *args, **kwargs):
            for key in ("password", "passwd"):
                if key in kwargs and isinstance(kwargs[key], str):
                    try:
                        kwargs[key] = kwargs[key].encode("latin1")
                    except UnicodeEncodeError:
                        kwargs[key] = kwargs[key].encode("utf-8")
            if "ssl_mode" in kwargs:
                ssl_mode = kwargs.pop("ssl_mode")
                if ssl_mode and str(ssl_mode).upper() != "DISABLED":
                    kwargs["ssl_verify_identity"] = True
                    kwargs["ssl_verify_cert"] = True
            return _orig_init(self, *args, **kwargs)

        pymysql.connections.Connection.__init__ = _patched_init
        pymysql.connections.Connection._is_ssl_mode_patched = True
    pymysql.install_as_MySQLdb()
except ImportError:
    pass

try:
    import re
    from django.db.backends.mysql.base import DatabaseWrapper
    from django.db.backends.mysql.schema import DatabaseSchemaEditor
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor

    DatabaseWrapper.check_database_version_supported = lambda self: None
    DatabaseSchemaEditor.sql_create_column_inline_fk = None

    _orig_skip_default = DatabaseSchemaEditor.skip_default
    def _tidb_skip_default(self, field):
        if field.get_internal_type() == "JSONField":
            return True
        return _orig_skip_default(self, field)
    DatabaseSchemaEditor.skip_default = _tidb_skip_default

    _orig_skip_default_on_alter = DatabaseSchemaEditor.skip_default_on_alter
    def _tidb_skip_default_on_alter(self, field):
        if field.get_internal_type() == "JSONField":
            return True
        return _orig_skip_default_on_alter(self, field)
    DatabaseSchemaEditor.skip_default_on_alter = _tidb_skip_default_on_alter

    def _clean_tidb_sql(sql):
        if not isinstance(sql, str):
            return sql
        # TiDB doesn't allow expression defaults on JSON columns, e.g. json DEFAULT ('[]') NOT NULL
        return re.sub(
            r"(?i)\bjson\b\s+DEFAULT\s*\([^)]*\)(\s+NOT\s+NULL)?",
            "json NULL",
            sql,
        )

    if not getattr(BaseDatabaseSchemaEditor, "_is_safe_execute_patched", False):
        _orig_execute = BaseDatabaseSchemaEditor.execute

        def _safe_execute(self, sql, params=()):
            sql = _clean_tidb_sql(sql)
            try:
                return _orig_execute(self, sql, params)
            except Exception as e:
                err_str = str(e).lower()
                if any(code in err_str for code in ["1060", "duplicate column", "1061", "duplicate key", "1050", "already exists", "1826"]):
                    print(f"⚠️ [TiDB Schema] Warning: Object already exists, skipping: {e}")
                    return
                raise

        BaseDatabaseSchemaEditor.execute = _safe_execute
        DatabaseSchemaEditor.execute = _safe_execute
        BaseDatabaseSchemaEditor._is_safe_execute_patched = True
except (ImportError, AttributeError):
    pass

def _can_connect_postgres(host, port):
    try:
        with socket.create_connection((host, int(port)), timeout=0.8):
            return True
    except (OSError, ValueError):
        return False

_database_url = env("DATABASE_URL", default="").strip()
_tidb_host = env("TIDB_HOST", default="").strip()
_tidb_password = env("TIDB_PASSWORD", default="").strip()
_pg_host = env("POSTGRES_HOST", default="localhost")
_pg_port = env("POSTGRES_PORT", default="5432")
_force_sqlite = env.bool("USE_SQLITE", default=False)

if _force_sqlite:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
elif (
    _database_url
    and _database_url.startswith(("mysql://", "mysqlclient://", "postgresql://", "postgres://", "sqlite://"))
    and "YOUR_TIDB_PASSWORD" not in _database_url
    and "<PASSWORD>" not in _database_url
    and "আপনার_আসল_পাসওয়ার্ড" not in _database_url
):
    DATABASES = {
        "default": env.db("DATABASE_URL")
    }
    if DATABASES["default"].get("ENGINE") == "django.db.backends.mysql":
        opts = DATABASES["default"].setdefault("OPTIONS", {})
        ssl_mode = opts.pop("ssl_mode", None)
        if ssl_mode and str(ssl_mode).upper() != "DISABLED":
            opts["ssl_verify_identity"] = True
            opts["ssl_verify_cert"] = True
elif _tidb_host and _tidb_password and "YOUR_TIDB_PASSWORD" not in _tidb_password:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": env("TIDB_DATABASE", default="test"),
            "USER": env("TIDB_USER", default="8iTvbQk1MzrmCrq.root"),
            "PASSWORD": _tidb_password,
            "HOST": _tidb_host,
            "PORT": env.int("TIDB_PORT", default=4000),
            "OPTIONS": {
                "ssl_verify_identity": True,
                "ssl_verify_cert": True,
                "charset": "utf8mb4",
            },
        }
    }
elif not _force_sqlite and _can_connect_postgres(_pg_host, _pg_port):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env("POSTGRES_DB", default="student_brain"),
            "USER": env("POSTGRES_USER", default="student_brain"),
            "PASSWORD": env("POSTGRES_PASSWORD", default="change-me"),
            "HOST": _pg_host,
            "PORT": _pg_port,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC & MEDIA FILES
# ============================================================

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# ============================================================
# MEDIA FILES (User Uploads)
# ============================================================
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ============================================================
# GEMINI AI SERVICE CONFIGURATION
# ============================================================
GEMINI_API_KEY = env("GEMINI_API_KEY", default=env("GOOGLE_API_KEY", default=""))


