# Generated by Django 6.0.7 on 2026-09-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='schedule',
            name='resources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
