# Generated by Django 6.1.1 on 2026-09-20 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('tracker', '0002_studygoal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studysession',
            options={'ordering': ['-session_date', 'start_time', '-created_at']},
        ),
        migrations.AddField(
            model_name='studysession',
            name='actual_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='actual_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_sessions', to='materials.course'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='extended_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studysession',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_sessions', to='materials.studymaterial'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='quiz_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='quiz_results',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studysession',
            name='quiz_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='quiz_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studysession',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('missed', 'Missed / Expired'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
