from django.urls import path

from .views import (
    CompleteSessionView,
    ExtendSessionView,
    GenerateSessionQuizView,
    RewardsListView,
    StartSessionView,
    StreakSummaryView,
    StudyGoalView,
    StudySessionDetailView,
    StudySessionListCreateView,
    SubmitSessionQuizView,
)

urlpatterns = [
    path(
        "sessions/",
        StudySessionListCreateView.as_view(),
        name="study-session-list-create",
    ),
    path(
        "sessions/<int:pk>/",
        StudySessionDetailView.as_view(),
        name="study-session-detail",
    ),
    path(
        "sessions/<int:pk>/start/",
        StartSessionView.as_view(),
        name="study-session-start",
    ),
    path(
        "sessions/<int:pk>/complete/",
        CompleteSessionView.as_view(),
        name="study-session-complete",
    ),
    path(
        "sessions/<int:pk>/extend/",
        ExtendSessionView.as_view(),
        name="study-session-extend",
    ),
    path(
        "sessions/<int:pk>/quiz/generate/",
        GenerateSessionQuizView.as_view(),
        name="study-session-quiz-generate",
    ),
    path(
        "sessions/<int:pk>/quiz/submit/",
        SubmitSessionQuizView.as_view(),
        name="study-session-quiz-submit",
    ),
    path(
        "streaks/",
        StreakSummaryView.as_view(),
        name="tracker-streaks",
    ),
    path(
        "rewards/",
        RewardsListView.as_view(),
        name="tracker-rewards",
    ),
    path(
        "goal/",
        StudyGoalView.as_view(),
        name="tracker-goal",
    ),
]
