# Generated by Django 6.1.1 on 2026-09-08 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_leaderboardprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='code_language',
            field=models.CharField(blank=True, default='python', max_length=50),
        ),
        migrations.AddField(
            model_name='comment',
            name='code_solution',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_helpful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='code_language',
            field=models.CharField(blank=True, default='python', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='code_snippet',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='solved_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='community.comment'),
        ),
        migrations.AddField(
            model_name='post',
            name='vscode_liveshare_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Exam Prep', 'Exam Prep'), ('Study Group', 'Study Group'), ('Course Help', 'Course Help'), ('Code Help', 'Code Help'), ('Resources', 'Resources')], default='General', max_length=50),
        ),
    ]
