# Generated by Django 6.1.1 on 2026-09-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_comment_code_language_comment_code_solution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyevent',
            name='max_participants',
            field=models.PositiveIntegerField(default=0, help_text='0 means unlimited slots for Going attendees'),
        ),
    ]
