# Generated by Django 6.1.1 on 2026-09-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_studyevent_max_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyevent',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='0 means unlimited slots for Going attendees', null=True),
        ),
    ]
