# Generated by Django 6.0.7 on 2026-09-02 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Lecture Note', 'Lecture Note'), ('Textbook Chapter', 'Textbook Chapter'), ('Cheat Sheet', 'Cheat Sheet'), ('Lab Report', 'Lab Report'), ('Research Paper', 'Research Paper'), ('Other', 'Other')], default='Lecture Note', max_length=50)),
                ('content', models.TextField(blank=True, default='')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('word_count', models.IntegerField(default=0)),
                ('is_analyzed', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True, default='')),
                ('key_topics', models.JSONField(blank=True, default=list)),
                ('key_concepts', models.JSONField(blank=True, default=list)),
                ('key_questions', models.JSONField(blank=True, default=list)),
                ('difficulty_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Intermediate', max_length=20)),
                ('estimated_reading_time', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
